services:
  flowise:
    image: flowiseai/flowise
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=Quest1@bj
      - FLOWISE_SECRETKEY=MQ-5RdU5actNn9jg2w-NEed9Gb6MYx2KHDdFTKdityY
    volumes:
      - flowise_data:/root
